version: '3'
services:
  activemq:
    build: ./activemq
    container_name : activemq
    ports:
    - "8161:8161"
  config:
    build: ./config
    container_name : config
    ports:
    - "8888:8888"
  gateway:
    build: ./gateway
    container_name : gateway
    ports:
    - "8080:8080"
